devices:
  - device_id: "cam_01"
    alias: "front_gate"
    stream_uri: "rtsp://admin:zhenjue888@10.0.0.248:554/Streaming/Channels/101"
    http_base_url: "http://10.0.0.248"
    username: "admin"
    password: "zhenjue888"
    stream_protocol: "rtsp"
    prefer_deepstream_decoder: false
    connection_timeout_ms: 8000
vision_params:
  marker_size_m: 1.00
  # 相机内参
  camera_matrix: [935.307, 0.0, 960.0, 0.0, 935.307, 540.0, 0.0, 0.0, 1.0]
  # 畸变系数
  dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]
  # 手眼标定矩阵
  t_cam2gripper: [-0.580001, 0.521740, -0.625608, 173.796416, 
                  -0.556683, 0.306827, 0.771986, -1265.117921, 
                  0.594729, 0.796018, 0.112484, 14207.169831, 
                  0.000000, 0.000000, 0.000000, 1.000000]
  # - device_id: "cam_02"
  #   alias: "rear_gate"
  #   stream_uri: "rtsp://admin:123456@192.168.1.65:554/Streaming/Channels/101"
  #   http_base_url: "http://192.168.1.65"
  #   username: "admin"
  #   password: "123456"
  #   stream_protocol: "rtsp"
  #   prefer_deepstream_decoder: true
  #   connection_timeout_ms: 8000
